# Generated by Django 4.1.1 on 2022-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="expiredate",
            field=models.DateField(verbose_name="expiredate"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
