# Generated by Django 4.1.1 on 2022-10-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_fooditem_expiredate_alter_fooditem_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="quantity",
            field=models.IntegerField(default="1"),
        ),
    ]
