# Generated by Django 3.2.16 on 2022-11-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='Good', max_length=100),
        ),
    ]
