# Generated by Django 3.2.16 on 2022-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='days_left',
            field=models.IntegerField(default=0),
        ),
    ]
