# Generated by Django 3.2.16 on 2022-11-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_item_days_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='days_left',
        ),
    ]
