# Generated by Django 3.2.16 on 2022-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_item_days_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
