# Generated by Django 3.2.16 on 2022-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_item_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Warning', 'Warning'), ('Good', 'Good')], default='Good', max_length=100),
        ),
    ]
