# Generated by Django 3.0.9 on 2022-11-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_item_daystill'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='humanize_time',
            field=models.IntegerField(default=0),
        ),
    ]
