# Generated by Django 3.0.9 on 2022-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_item_humanize_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='humanize_time1',
            field=models.IntegerField(default=0),
        ),
    ]
