# Generated by Django 3.0.9 on 2022-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_item_humanize_time1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wday',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
