# Generated by Django 3.0.9 on 2022-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_item_wday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wday',
            field=models.DateTimeField(blank=True, default='YYYY-MM-DD'),
        ),
    ]
