# Generated by Django 3.0.9 on 2022-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20221201_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wday',
            field=models.DateTimeField(),
        ),
    ]
