# Generated by Django 3.0.9 on 2022-12-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_item_wday'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='humanize_time2',
            field=models.IntegerField(default=0),
        ),
    ]
