# Generated by Django 3.0.9 on 2022-12-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_item_humanize_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='humanize_time2',
        ),
    ]
