# Generated by Django 3.0.9 on 2022-12-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_item_humanize_time2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='now1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
