# Generated by Django 3.0.9 on 2022-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_item_now1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valid1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
