# Generated by Django 3.0.9 on 2022-12-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_item_valid1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='now1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='valid1',
        ),
    ]
