# Generated by Django 3.0.9 on 2022-12-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20221203_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='humanize_time',
        ),
        migrations.RemoveField(
            model_name='item',
            name='humanize_time1',
        ),
    ]
