# Generated by Django 3.0.9 on 2022-12-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20221203_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
