# Generated by Django 3.0.9 on 2022-12-04 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20221203_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='humanize_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='humanize_time1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
